SELECT * FROM mbf.servicesList;

INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'coloring');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'color correction & new color');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'wash & style');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'blowout');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'facial');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'waxing');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'dermaplaning');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash extensions', 'lash removal');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash extensions', 'lash extensions');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash Extensions', 'classic bottom lash extensions');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash Extensions', 'hybrid lash extensions');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash Extensions', 'lash fill');
INSERT INTO servicesList (category, services_list_item) VALUES ('masseuse', 'foot');
INSERT INTO servicesList (category, services_list_item) VALUES ('masseuse', 'full body');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'beard trim');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'beard trim/hot towel/straight razor');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'childrens cut');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'edge up');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'haircut & beard trim');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'haircut & beard trim deluxe');

INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'hot lather head shave');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'mens haircut');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'shampoo');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'razor fade');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'skin fade');
INSERT INTO servicesList (category, services_list_item) VALUES ('barber', 'taper fade');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'braid updo');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'childrens braids');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'box braids (mid-back length)');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'box braids (waist length)');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'cornrows');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'crochet');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'french braids');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'goddess');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'goddess faux locs');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'lemonade');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'marley twist');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'senegalese twist');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'spring twist');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'two-layer braids');
INSERT INTO servicesList (category, services_list_item) VALUES ('braid specialist', 'yarn faux locs');

INSERT INTO servicesList (category, services_list_item) VALUES ('trichology', 'consultation');
INSERT INTO servicesList (category, services_list_item) VALUES ('trichology', 'moisturizing treatment');
INSERT INTO servicesList (category, services_list_item) VALUES ('trichology', 'sebum treatment');
INSERT INTO servicesList (category, services_list_item) VALUES ('nail tech', 'acrylic nails');
INSERT INTO servicesList (category, services_list_item) VALUES ('nail tech', 'gel nails');
INSERT INTO servicesList (category, services_list_item) VALUES ('nail tech', 'gel manicure');
INSERT INTO servicesList (category, services_list_item) VALUES ('nail tech', 'manicure');
INSERT INTO servicesList (category, services_list_item) VALUES ('nail tech', 'gel pedicure');
INSERT INTO servicesList (category, services_list_item) VALUES ('nail tech', 'pedicure');
INSERT INTO servicesList (category, services_list_item) VALUES ('nail tech', 'silk wrap Nails');
INSERT INTO servicesList (category, services_list_item) VALUES ('nail tech', 'sns nails');
INSERT INTO servicesList (category, services_list_item) VALUES ('nail tech', '3Ds acrylic nails');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'bridal');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'bridal party');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'glam');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'in studio');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'on location');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'brow wax & tint');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'microblading');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'private 1on1');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'prom');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'special event');
INSERT INTO servicesList (category, services_list_item) VALUES ('makeup artist', 'tv/production');

INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'bottom classic');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'classic');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'classic 2 week fill');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'classic 3 week fill');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'classic 4 week fill');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'hybrid');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'hybrid 2 week fill');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'hybrid 3 week fill');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'volume');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'volume 2 week fill');
INSERT INTO servicesList (category, services_list_item) VALUES ('lash artist', 'volume 3 week fill');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'children');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Color Services - Bayalage');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Color Services - Bleach & Tone');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Color Services - Color Correction');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Color Services - Demi Color Rinse/Glaze Toner');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Color Services - Highlight-Full Head');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Color Services - Partial Highlight');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Color Services - Single Process Color');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Color Services - Double processing color');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Color Services - Touch-Up');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Deep Condition');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Dominican Blowout');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Extensions');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Hair Trim');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Haircuts - Designer Cut');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Haircuts - Womens Haircut');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Haircuts - Mens Haircut');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Hot Oil Treatment');

INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Keratin Treatment - Starter Loc');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Keratin Treatment - Loc Maintenance (Baby Locs)');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Keratin Treatment - Loc Maintenance (Teen Locs)');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Keratin Treatment - Loc Maintenance (Full Grown)');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Keratin Treatment - Loc Styling');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Keratin Treatment - Loc Color');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Keratin Treatment - Loc Detox');

INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Big Chop Transition Service');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Blowout');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Braid Out');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Coil/Comb Twist');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Crochet Braids');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Flat Twist Out');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Rod Set/Natural Hair');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Shingling');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Silk Press');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Two Strand Twist');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Natural Hair - Two Strand Twist Updo');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Perm');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Protein Treatment');
INSERT INTO servicesList (category, services_list_item) VALUES ('hair stylist', 'Steam Treatment');

INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Body Wraps');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Chemical Peels');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Face & Body Masks');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Back Wax');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Brazilian Bikini Wax');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Bikini Wax');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Chin Wax');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Leg Wax');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Stomach Wax');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Microdermabrasion');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Microneedling');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Laser Resurfacing');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Light Therapy');
INSERT INTO servicesList (category, services_list_item) VALUES ('esthetician', 'Sugaring');